development:
  server: "http://faye:4242/stream"
  secret_token: "secret"
test:
  server: "http://faye:4242/stream"
  secret_token: "secret"
production:
  server: "http://example.com/faye"
  secret_token: "9eba1078bbb9289f949f51abc7ed5f842fed3af11374056bf09799e4ef2733f2"
  signature_expiration: 3600 # one hour
